### ISSUE TITLE
Examples panic

### ISSUE THREAD

**Issue by johanhelsing** [Leafwing-Studios/leafwing-input-manager#406]
## Version

main, fc3e3486e402312b2206f09ab8585c39543f3df4

## Operating system & version

Windows 11

## What you did

```
cargo run --example minimal
```

## What you expected to happen

The example should run without errors

## What actually happened
```
dev/leafwing-input-manager main cargo run --example minimal
   Compiling leafwing-input-manager v0.10.0 (C:\Users\Johan\dev\leafwing-input-manager)
    Finished dev [optimized + debuginfo] target(s) in 6.84s
     Running `target\debug\examples\minimal.exe`
2023-11-02T07:57:21.624296Z  INFO bevy_winit::system: Creating new window "App" (0v0)
thread 'main' panicked at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.2\src\compose\comment_strip_iter.rs:6:67:
called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    (\/\/|\/\*|\*\/)
     ^^
error: unrecognized escape sequence
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:595
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\result.rs:1652
   3: enum2$<core::result::Result<regex::re_unicode::Regex,enum2$<regex::error::Error> > >::unwrap
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\result.rs:1077
   4: naga_oil::compose::comment_strip_iter::RE_COMMENT::closure$0
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.2\src\compose\comment_strip_iter.rs:6
   5: core::ops::function::FnOnce::call_once<naga_oil::compose::comment_strip_iter::RE_COMMENT::closure_env$0,tuple$<> >
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250
   6: once_cell::sync::impl$6::get_or_init::closure$0
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\once_cell-1.18.0\src\lib.rs:1122
   7: once_cell::imp::impl$4::initialize::closure$0<regex::re_unicode::Regex,once_cell::sync::impl$6::get_or_init::closure_env$0<regex::re_unicode::Regex,once_cell::sync::impl$11::force::closure_env$0<regex::re_unicode::Regex,regex::re_unicode::Regex (*)()> >,e
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\once_cell-1.18.0\src\imp_std.rs:72
   8: core::ops::function::impls::impl$3::call_mut
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:294
   9: once_cell::imp::initialize_or_wait
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\once_cell-1.18.0\src\imp_std.rs:196
  10: once_cell::imp::OnceCell<regex::re_unicode::Regex>::initialize<regex::re_unicode::Regex,once_cell::sync::impl$6::get_or_init::closure_env$0<regex::re_unicode::Regex,once_cell::sync::impl$11::force::closure_env$0<regex::re_unicode::Regex,regex::re_unicode:
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\once_cell-1.18.0\src\imp_std.rs:68
  11: once_cell::sync::OnceCell<regex::re_unicode::Regex>::get_or_try_init
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\once_cell-1.18.0\src\lib.rs:1163
  12: once_cell::sync::OnceCell<regex::re_unicode::Regex>::get_or_init
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\once_cell-1.18.0\src\lib.rs:1122
  13: once_cell::sync::Lazy<regex::re_unicode::Regex,regex::re_unicode::Regex (*)()>::force
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\once_cell-1.18.0\src\lib.rs:1311
  14: once_cell::sync::impl$12::deref
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\once_cell-1.18.0\src\lib.rs:1378
  15: naga_oil::compose::comment_strip_iter::impl$0::next
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.2\src\compose\comment_strip_iter.rs:18
  16: naga_oil::compose::preprocess::Preprocessor::get_preprocessor_metadata
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.2\src\compose\preprocess.rs:400
  17: naga_oil::compose::get_preprocessor_data
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.2\src\compose\mod.rs:1889
  18: bevy_render::render_resource::shader::Shader::preprocess
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\render_resource\shader.rs:42
  19: bevy_render::render_resource::shader::Shader::from_wgsl
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\render_resource\shader.rs:71
  20: bevy_render::view::window::screenshot::impl$1::build
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\view\window\screenshot.rs:132
  21: bevy_app::app::App::add_boxed_plugin
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\app.rs:713
  22: bevy_app::plugin::sealed::impl$0::add_to_app
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\plugin.rs:94
  23: bevy_app::app::App::add_plugins
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\app.rs:803
  24: bevy_render::view::window::impl$0::build
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\view\window.rs:37
  25: bevy_app::app::App::add_boxed_plugin
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\app.rs:713
  26: bevy_app::plugin::sealed::impl$0::add_to_app
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\plugin.rs:94
  27: bevy_app::plugin::sealed::impl$9::add_to_app<bevy_app::plugin::sealed::PluginMarker,bevy_hierarchy::valid_parent_check_plugin::ValidParentCheckPlugin<bevy_render::view::visibility::ComputedVisibility>,bevy_app::plugin::sealed::PluginMarker,bevy_render::vi
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\plugin.rs:118
  28: bevy_render::impl$3::build
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\lib.rs:331
  29: bevy_app::app::App::add_boxed_plugin
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\app.rs:713
  30: bevy_app::plugin_group::PluginGroupBuilder::finish
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\plugin_group.rs:181
  31: bevy_app::plugin::sealed::impl$1::add_to_app
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\plugin.rs:105
  32: bevy_app::app::App::add_plugins
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\app.rs:803
  33: minimal::main
             at .\examples\minimal.rs:5
  34: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\minimal.exe` (exit code: 101)
```

**Comment by johanhelsing** [comment]
Ooops. Seems I just had some outdated deps. Gone after `cargo update`
